name: MVP (Fase 1)

on:
  push:  
    branches: [ "main" ]
  pull_request:  
    branches: [ "main" ]

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:  
    - name: Checkout code
      uses: actions/checkout@v4  

    - name: Set up Python 3.10
      uses: actions/setup-python@v4  
      with:  
        python-version: "3.10"  

    - name: Install dependencies
      run: |
        pip install uv
        uv venv .venv  
        source .venv/bin/activate  
        uv pip install -r fase_1_mvp/requirements.txt  

    - name: Run tests
      run: |  
        source .venv/bin/activate  
        uv run pytest
