name: CI Pipeline  # Nome da pipeline  

on:  # Quando a pipeline será acionada?  
  push:  
    branches: [ "main" ]  # Só roda quando houver push na branch main  
  pull_request:  
    branches: [ "main" ]  # Roda em PRs direcionadas à main  

jobs:  
  test:  # Job de testes  
    runs-on: ubuntu-latest  # Executa em máquina virtual Ubuntu  

    steps:  
    - name: Checkout code  # Baixa o código do repositório  
      uses: actions/checkout@v4  

    - name: Set up Python 3.10  # Configura o Python  
      uses: actions/setup-python@v4  
      with:  
        python-version: "3.10"  

    - name: Install dependencies  # Instala dependências com uv  
      run: |  
        uv venv .venv  
        source .venv/bin/activate  
        uv pip install -r fase_1_mvp/requirements.txt  

    - name: Run tests  # Executa testes (você precisará criar testes depois)  
      run: |  
        source .venv/bin/activate  
        python -m pytest fase_1_mvp/tests/  
